# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RiskTypeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('pos', models.IntegerField()),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('risktypefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insurance.RiskTypeField')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('insurance.risktypefield',),
        ),
        migrations.CreateModel(
            name='TextValue',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insurance.Value')),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('insurance.value',),
        ),
        migrations.AddField(
            model_name='value',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.RiskTypeField'),
        ),
        migrations.AddField(
            model_name='value',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_insurance.value_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='value',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Risk'),
        ),
        migrations.AddField(
            model_name='risktypefield',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_insurance.risktypefield_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='risktypefield',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.RiskType'),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.RiskType'),
        ),
    ]
