# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20181203_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateField',
            fields=[
                ('risktypefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insurance.RiskTypeField')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('insurance.risktypefield',),
        ),
        migrations.CreateModel(
            name='DateValue',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insurance.Value')),
                ('value', models.DateField()),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('insurance.value',),
        ),
    ]
